version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: wolfx0-elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0  # Critical for external access
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TRANSPORT_PORT}:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data:

